# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class CoffeeKind(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Beans, grind coffee, capsules or instant
    """


    class MetaOapg:
        enum_value_to_name = {
            "beans": "BEANS",
            "ground": "GROUND",
            "capsules": "CAPSULES",
            "instant": "INSTANT",
        }
    
    @schemas.classproperty
    def BEANS(cls):
        return cls("beans")
    
    @schemas.classproperty
    def GROUND(cls):
        return cls("ground")
    
    @schemas.classproperty
    def CAPSULES(cls):
        return cls("capsules")
    
    @schemas.classproperty
    def INSTANT(cls):
        return cls("instant")
