# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_account_logout.get import GetApiV1AccountLogout
from openapi_client.paths.api_v1_account_register_verify.get import GetApiV1AccountRegisterVerify
from openapi_client.paths.api_v1_account_login.post import PostApiV1AccountLogin
from openapi_client.paths.api_v1_account_password_reset.post import PostApiV1AccountPasswordReset
from openapi_client.paths.api_v1_account_password_reset_verify.post import PostApiV1AccountPasswordResetVerify
from openapi_client.paths.api_v1_account_register.post import PostApiV1AccountRegister
from openapi_client.paths.api_v1_account_register_resend.post import PostApiV1AccountRegisterResend
from openapi_client.paths.api_v1_account_token_refresh.post import PostApiV1AccountTokenRefresh
from openapi_client.paths.api_v1_account_token_verify.post import PostApiV1AccountTokenVerify


class AccountAccountApi(
    GetApiV1AccountLogout,
    GetApiV1AccountRegisterVerify,
    PostApiV1AccountLogin,
    PostApiV1AccountPasswordReset,
    PostApiV1AccountPasswordResetVerify,
    PostApiV1AccountRegister,
    PostApiV1AccountRegisterResend,
    PostApiV1AccountTokenRefresh,
    PostApiV1AccountTokenVerify,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
