# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_roaster_roaster_id.delete import DeleteApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.delete import DeleteApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_account_logout.get import GetApiV1AccountLogout
from openapi_client.paths.api_v1_account_register_verify.get import GetApiV1AccountRegisterVerify
from openapi_client.paths.api_v1_coffee.get import GetApiV1Coffee
from openapi_client.paths.api_v1_roaster.get import GetApiV1Roaster
from openapi_client.paths.api_v1_roaster_roaster_id.get import GetApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee.get import GetApiV1RoasterRoasteridCoffee
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.get import GetApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_roaster_roaster_id.patch import PatchApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.patch import PatchApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_account_login.post import PostApiV1AccountLogin
from openapi_client.paths.api_v1_account_password_reset.post import PostApiV1AccountPasswordReset
from openapi_client.paths.api_v1_account_password_reset_verify.post import PostApiV1AccountPasswordResetVerify
from openapi_client.paths.api_v1_account_register.post import PostApiV1AccountRegister
from openapi_client.paths.api_v1_account_register_resend.post import PostApiV1AccountRegisterResend
from openapi_client.paths.api_v1_account_token_refresh.post import PostApiV1AccountTokenRefresh
from openapi_client.paths.api_v1_account_token_verify.post import PostApiV1AccountTokenVerify
from openapi_client.paths.api_v1_roaster.post import PostApiV1Roaster
from openapi_client.paths.api_v1_roaster_roaster_id_coffee.post import PostApiV1RoasterRoasteridCoffee
from openapi_client.paths.api_v1_roaster_roaster_id.put import PutApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.put import PutApiV1RoasterRoasteridCoffeeCoffeeid


class AllApi(
    DeleteApiV1RoasterRoasterid,
    DeleteApiV1RoasterRoasteridCoffeeCoffeeid,
    GetApiV1AccountLogout,
    GetApiV1AccountRegisterVerify,
    GetApiV1Coffee,
    GetApiV1Roaster,
    GetApiV1RoasterRoasterid,
    GetApiV1RoasterRoasteridCoffee,
    GetApiV1RoasterRoasteridCoffeeCoffeeid,
    PatchApiV1RoasterRoasterid,
    PatchApiV1RoasterRoasteridCoffeeCoffeeid,
    PostApiV1AccountLogin,
    PostApiV1AccountPasswordReset,
    PostApiV1AccountPasswordResetVerify,
    PostApiV1AccountRegister,
    PostApiV1AccountRegisterResend,
    PostApiV1AccountTokenRefresh,
    PostApiV1AccountTokenVerify,
    PostApiV1Roaster,
    PostApiV1RoasterRoasteridCoffee,
    PutApiV1RoasterRoasterid,
    PutApiV1RoasterRoasteridCoffeeCoffeeid,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
