# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_account_password_reset.post import PostApiV1AccountPasswordReset
from openapi_client.paths.api_v1_account_password_reset_verify.post import PostApiV1AccountPasswordResetVerify


class PasswordAccountPasswordApi(
    PostApiV1AccountPasswordReset,
    PostApiV1AccountPasswordResetVerify,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
