# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_roaster_roaster_id.delete import DeleteApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.delete import DeleteApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_roaster.get import GetApiV1Roaster
from openapi_client.paths.api_v1_roaster_roaster_id.get import GetApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee.get import GetApiV1RoasterRoasteridCoffee
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.get import GetApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_roaster_roaster_id.patch import PatchApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.patch import PatchApiV1RoasterRoasteridCoffeeCoffeeid
from openapi_client.paths.api_v1_roaster.post import PostApiV1Roaster
from openapi_client.paths.api_v1_roaster_roaster_id_coffee.post import PostApiV1RoasterRoasteridCoffee
from openapi_client.paths.api_v1_roaster_roaster_id.put import PutApiV1RoasterRoasterid
from openapi_client.paths.api_v1_roaster_roaster_id_coffee_coffee_id.put import PutApiV1RoasterRoasteridCoffeeCoffeeid


class RoasterRoasterApi(
    DeleteApiV1RoasterRoasterid,
    DeleteApiV1RoasterRoasteridCoffeeCoffeeid,
    GetApiV1Roaster,
    GetApiV1RoasterRoasterid,
    GetApiV1RoasterRoasteridCoffee,
    GetApiV1RoasterRoasteridCoffeeCoffeeid,
    PatchApiV1RoasterRoasterid,
    PatchApiV1RoasterRoasteridCoffeeCoffeeid,
    PostApiV1Roaster,
    PostApiV1RoasterRoasteridCoffee,
    PutApiV1RoasterRoasterid,
    PutApiV1RoasterRoasteridCoffeeCoffeeid,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
