# coding: utf-8

"""
    Coffee Freaks API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1-178-83b5c11-SNAPSHOT
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.api_v1_account_token_refresh.post import PostApiV1AccountTokenRefresh
from openapi_client.paths.api_v1_account_token_verify.post import PostApiV1AccountTokenVerify


class TokenAccountTokenApi(
    PostApiV1AccountTokenRefresh,
    PostApiV1AccountTokenVerify,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
